package com.example.thirtydays.ui.theme

import androidx.compose.ui.graphics.Color

// Палитра Material 3 (схема Tonal Spot), сгенерирована из базового цвета #00897B
// тем же алгоритмом, что использует Material Theme Builder (material-color-utilities).

val primaryLight = Color(0xFF1F6A60)
val onPrimaryLight = Color(0xFFE2FFF8)
val primaryContainerLight = Color(0xFFA9F0E3)
val onPrimaryContainerLight = Color(0xFF085C53)
val secondaryLight = Color(0xFF4B645F)
val onSecondaryLight = Color(0xFFE3FFF8)
val secondaryContainerLight = Color(0xFFCCE8E2)
val onSecondaryContainerLight = Color(0xFF3E5752)
val tertiaryLight = Color(0xFF336577)
val onTertiaryLight = Color(0xFFF2FAFF)
val tertiaryContainerLight = Color(0xFFB2E4FA)
val onTertiaryContainerLight = Color(0xFF205466)
val errorLight = Color(0xFFA83836)
val onErrorLight = Color(0xFFFFF7F6)
val errorContainerLight = Color(0xFFFA746F)
val onErrorContainerLight = Color(0xFF6E0A12)
val backgroundLight = Color(0xFFF6FAF8)
val onBackgroundLight = Color(0xFF2A3432)
val surfaceLight = Color(0xFFF6FAF8)
val onSurfaceLight = Color(0xFF2A3432)
val surfaceVariantLight = Color(0xFFDAE5E1)
val onSurfaceVariantLight = Color(0xFF56615F)
val outlineLight = Color(0xFF727D7A)
val outlineVariantLight = Color(0xFFA9B4B1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF0A0F0E)
val inverseOnSurfaceLight = Color(0xFF999E9C)
val inversePrimaryLight = Color(0xFFB4FCEE)
val surfaceDimLight = Color(0xFFD1DCD9)
val surfaceBrightLight = Color(0xFFF6FAF8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEEF5F2)
val surfaceContainerLight = Color(0xFFE7F0ED)
val surfaceContainerHighLight = Color(0xFFE1EAE7)
val surfaceContainerHighestLight = Color(0xFFDAE5E1)

val primaryDark = Color(0xFF9CD1C7)
val onPrimaryDark = Color(0xFF104841)
val primaryContainerDark = Color(0xFF275B53)
val onPrimaryContainerDark = Color(0xFFB8EEE3)
val secondaryDark = Color(0xFFB1CCC6)
val onSecondaryDark = Color(0xFF2C4540)
val secondaryContainerDark = Color(0xFF27403C)
val onSecondaryContainerDark = Color(0xFFAAC5BF)
val tertiaryDark = Color(0xFFCFF0FF)
val onTertiaryDark = Color(0xFF2A5D6F)
val tertiaryContainerDark = Color(0xFFB2E4FA)
val onTertiaryContainerDark = Color(0xFF205466)
val errorDark = Color(0xFFFA746F)
val onErrorDark = Color(0xFF490006)
val errorContainerDark = Color(0xFF871F21)
val onErrorContainerDark = Color(0xFFFF9993)
val backgroundDark = Color(0xFF0A0F0E)
val onBackgroundDark = Color(0xFFDDE8E4)
val surfaceDark = Color(0xFF0A0F0E)
val onSurfaceDark = Color(0xFFDDE8E4)
val surfaceVariantDark = Color(0xFF1E2826)
val onSurfaceVariantDark = Color(0xFFA2ADAA)
val outlineDark = Color(0xFF6D7875)
val outlineVariantDark = Color(0xFF3F4A48)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF6FAF8)
val inverseOnSurfaceDark = Color(0xFF515654)
val inversePrimaryDark = Color(0xFF35685F)
val surfaceDimDark = Color(0xFF0A0F0E)
val surfaceBrightDark = Color(0xFF242E2C)
val surfaceContainerLowestDark = Color(0xFF000000)
val surfaceContainerLowDark = Color(0xFF0E1513)
val surfaceContainerDark = Color(0xFF131B1A)
val surfaceContainerHighDark = Color(0xFF19211F)
val surfaceContainerHighestDark = Color(0xFF1E2826)
